services:
  service_postgres:
    image: postgres:15.1-alpine
    container_name: container_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb01
    ports:
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./docker/postgres_service/initdb.d:/docker-entrypoint-initdb.d

  service_pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: container_pgadmin
    ports:
      - 8081:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - service_postgres

  service_golang:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: container_golang
    volumes:
      - .:/app
    working_dir: /app
    command: ["sleep", "infinity"]
    ports:
      - "8080:8080"

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
